# Generated by Django 2.2 on 2019-05-29 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baglanti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan', models.CharField(max_length=200)),
                ('ilan_id', models.IntegerField()),
                ('isim', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('mesaj', models.TextField(blank=True)),
                ('baglanti_zamani', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
