# Generated by Django 2.2 on 2019-05-29 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emlakci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('aciklama', models.TextField(blank=True)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('is_mvp', models.BooleanField(default=False)),
                ('kira_tarihi', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
