# Generated by Django 2.2 on 2019-05-29 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emlakcilar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('sehir', models.CharField(max_length=100)),
                ('bolge', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('kategori', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('fiyat', models.IntegerField()),
                ('yatakodasi', models.IntegerField()),
                ('banyo', models.IntegerField()),
                ('garaj', models.IntegerField(default=0)),
                ('metrekare', models.IntegerField()),
                ('oda', models.CharField(max_length=50)),
                ('foto_ana', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('foto_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('foto_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('foto_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('foto_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('foto_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('foto_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('yayinlandi', models.BooleanField(default=True)),
                ('liste_tarihi', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('emlakci', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emlakcilar.Emlakci')),
            ],
        ),
    ]
